import {
  eighthCard,
  fifthCard,
  firstCard,
  footerLight,
  fourthCard,
  lightBackground,
  ninthCard,
  searchFocusLight,
  searchLight,
  secondCard,
  seventhCard,
  sixthCard,
  tenthCard,
  tertiary,
  textCard,
  textGrayLight,
  textLight,
  textLightSecondary,
  thirdCard,
  lightHeader,
  lightHeaderSecondary,
} from "./variableColors";

export const lightTheme = {
  name: "light",
  colors: {
    header: lightHeader,
    header_secondary: lightHeaderSecondary,
    close_accessibility: "red",
    primary: lightBackground,
    tertiary: tertiary,
    footer: footerLight,
    text: textLight,
    textSecondary: textLightSecondary,
    textGray: textGrayLight,
    textCard: textCard,
    search: searchLight,
    searchFocus: searchFocusLight,
    cards: {
      0: firstCard,
      1: secondCard,
      2: thirdCard,
      3: fourthCard,
      4: fifthCard,
      5: sixthCard,
      6: seventhCard,
      7: eighthCard,
      8: ninthCard,
      9: tenthCard,
    },
  },
};
